(* SPDX-License-Identifier: Apache-2.0 *)
section \<open>Saptabhangi: the Jaina sevenfold predication, and what \<open>syat\<close> is doing\<close>

theory Jaina_Saptabhangi
  imports Catuskoti
begin

text \<open>
  The Jaina \<open>saptabhangi\<close> (the sevenfold predication, the logical face of
  \<open>anekantavada\<close>) states, of any claim, seven modes, each prefixed
  by \<open>syat\<close> ("in some respect"):

  \<^enum> \<open>syad asti\<close> -- in some respect it is;
  \<^enum> \<open>syan nasti\<close> -- in some respect it is not;
  \<^enum> \<open>syad asti ca nasti ca\<close> -- in some respect it is and is not (successively);
  \<^enum> \<open>syad avaktavyah\<close> -- in some respect it is inexpressible (both at once);
  \<^enum> \<open>syad asti ca avaktavyas ca\<close>;
  \<^enum> \<open>syan nasti ca avaktavyas ca\<close>;
  \<^enum> \<open>syad asti ca nasti ca avaktavyas ca\<close>.

  This is not Buddhist material. It is included because it is the other
  Indian answer to the question the \<open>catuskoti\<close> asks, and because the
  fourth mode -- the inexpressible -- is exactly the kind of value Priest's
  fifth value \<open>E\<close> was introduced to be. The comparison can therefore be
  made inside the semantics this session already has, rather than asserted.

  Three readings are examined, and they come apart sharply.

  \<^item> \<^bold>\<open>Truth-functional\<close>: read \<open>avaktavya\<close> as the value \<open>E\<close> and the modes as
    compounds. Since \<open>E\<close> is absorbing, modes 4 to 7 take the same value, so
    seven modes have at most four values. This is the same negative shape as
    Jizang's ladder in \<open>Madhyamaka_Jizang\<close>.

  \<^item> \<^bold>\<open>Classificatory\<close>: read the modes as classifications of one value, the
    way \<open>koti_of\<close> classifies. Then modes 5 to 7 are outright unsatisfiable,
    because a value has exactly one \<open>koti\<close>; the realizable modes are exactly
    the four corners. So on a single valuation the sevenfold scheme is the
    fourfold scheme.

  \<^item> \<^bold>\<open>Indexical\<close>: read \<open>syat\<close> as quantifying over respects (\<open>naya\<close>), so that a
    mode is a claim about a family of valuations. Then all seven modes are
    satisfiable, pairwise separable, and generated by three independent
    primitives -- the traditional description of the scheme as the seven
    non-empty combinations of three.

  Within the indexical encoding, the mixed modes need at least two respects
  and the seventh needs three. These are measurements of this selected
  semantics, not a claim that every historical reading has this structure.
\<close>

datatype bhanga = B1 | B2 | B3 | B4 | B5 | B6 | B7

lemma UNIV_bhanga: "(UNIV :: bhanga set) = {B1, B2, B3, B4, B5, B6, B7}"
proof -
  have "b \<in> {B1, B2, B3, B4, B5, B6, B7}" for b by (cases b) auto
  then show ?thesis by auto
qed


subsection \<open>Truth-functional reading: the inexpressible absorbs modes 4 to 7\<close>

text \<open>
  Each mode is the compound its name describes, with \<open>avaktavya\<close> the
  ineffable value \<open>E\<close>. Conjunction with \<open>E\<close> is \<open>E\<close>, so the last four modes
  are indistinguishable.
\<close>

fun bh_val :: "tv5 \<Rightarrow> bhanga \<Rightarrow> tv5" where
  "bh_val x B1 = x"
| "bh_val x B2 = neg5 x"
| "bh_val x B3 = conj5 x (neg5 x)"
| "bh_val x B4 = E"
| "bh_val x B5 = conj5 x E"
| "bh_val x B6 = conj5 (neg5 x) E"
| "bh_val x B7 = conj5 (conj5 x (neg5 x)) E"

theorem avaktavya_absorbs:
  "bh_val x B4 = E" "bh_val x B5 = E" "bh_val x B6 = E" "bh_val x B7 = E"
  by simp_all

lemma bh_val_range: "range (bh_val x) = {x, neg5 x, conj5 x (neg5 x), E}"
proof -
  have "range (bh_val x) = bh_val x ` {B1, B2, B3, B4, B5, B6, B7}"
    by (simp add: UNIV_bhanga)
  also have "\<dots> = {x, neg5 x, conj5 x (neg5 x), E}" by auto
  finally show ?thesis .
qed

theorem saptabhangi_not_truth_functional:
  "B4 \<noteq> B5" "B5 \<noteq> B6" "B6 \<noteq> B7"
  "bh_val x B4 = bh_val x B5" "bh_val x B5 = bh_val x B6" "bh_val x B6 = bh_val x B7"
  by simp_all

text \<open>
  Seven syntactically distinct modes, at most four values, for every input.
\<close>

theorem seven_modes_four_values: "card (range (bh_val x)) \<le> 4"
proof -
  have "card {x, neg5 x, conj5 x (neg5 x), E} \<le> 4"
    by (auto simp: card_insert_if)
  then show ?thesis by (simp add: bh_val_range)
qed


subsection \<open>Classificatory reading: the realizable modes are the four corners\<close>

text \<open>
  Read instead as classifications of a single value: \<open>asti\<close> is corner
  \<open>K1\<close>, \<open>nasti\<close> is \<open>K2\<close>, the successive both is \<open>K3\<close>, and the inexpressible
  is \<open>K4\<close>. A value has exactly one corner (\<open>koti_total\<close>), so the modes that
  ask for two corners at once are empty.
\<close>

context mv_logic
begin

definition bh_holds :: "'v \<Rightarrow> bhanga \<Rightarrow> bool" where
  "bh_holds x b =
     (case b of
        B1 \<Rightarrow> koti_of x = K1
      | B2 \<Rightarrow> koti_of x = K2
      | B3 \<Rightarrow> koti_of x = K3
      | B4 \<Rightarrow> koti_of x = K4
      | B5 \<Rightarrow> koti_of x = K1 \<and> koti_of x = K4
      | B6 \<Rightarrow> koti_of x = K2 \<and> koti_of x = K4
      | B7 \<Rightarrow> koti_of x = K3 \<and> koti_of x = K4)"

theorem mixed_modes_unsatisfiable:
  "\<not> bh_holds x B5" "\<not> bh_holds x B6" "\<not> bh_holds x B7"
  by (simp_all add: bh_holds_def)

lemma bh_holds_corners:
  "bh_holds x B1 \<longleftrightarrow> koti_of x = K1"
  "bh_holds x B2 \<longleftrightarrow> koti_of x = K2"
  "bh_holds x B3 \<longleftrightarrow> koti_of x = K3"
  "bh_holds x B4 \<longleftrightarrow> koti_of x = K4"
  by (simp_all add: bh_holds_def)

end

lemma fde5_koti_values:
  "fde5.koti_of (Fin T) = K1"
  "fde5.koti_of (Fin F) = K2"
  "fde5.koti_of (Fin B) = K3"
  "fde5.koti_of (Fin N) = K4"
  by (simp_all add: fde5.koti_of_def neg4_def mk_def)

theorem fde5_saptabhangi_realizable_is_catuskoti:
  "{b. \<exists>x. fde5.bh_holds x b} = {B1, B2, B3, B4}"
proof (intro equalityI subsetI)
  fix b :: bhanga
  assume "b \<in> {b. \<exists>x. fde5.bh_holds x b}"
  then show "b \<in> {B1, B2, B3, B4}"
    by (cases b) (auto simp: fde5.mixed_modes_unsatisfiable)
next
  fix b :: bhanga
  assume "b \<in> {B1, B2, B3, B4}"
  then show "b \<in> {b. \<exists>x. fde5.bh_holds x b}"
    using fde5_koti_values fde5_koti_of_E
    by (cases b) (auto simp: fde5.bh_holds_corners)
qed

text \<open>
  In this encoding, \<open>E\<close> has the same fourth-corner classification as the
  gap. This equality of designatedness profiles does not identify the
  historical meanings of ineffability, a truth-value gap, or silence.
\<close>

theorem avaktavya_is_the_fourth_corner: "fde5.bh_holds E B4"
  by (simp add: fde5.bh_holds_corners fde5_koti_of_E)

text \<open>
  If the ineffable is designated instead -- the \<open>fde5D\<close> instance, which is
  how universal designation treats a valueless claim -- the inexpressible
  stops being the fourth corner and becomes a glut.
\<close>

theorem avaktavya_designated_is_a_glut: "fde5D.koti_of E = K3"
  by (simp add: fde5D.koti_of_def)


subsection \<open>Indexical reading: \<open>syat\<close> quantifies over respects\<close>

text \<open>
  A valuation family \<open>V\<close> assigns a value in each respect. Positive and
  negative support are existential; ineffability is a third independent
  existential support. The model contains no ordering or simultaneity
  relation. Thus it abstracts away the traditional distinction between
  successive predication in the third mode and simultaneous predication
  associated with the fourth; \<open>E\<close> is not derived from positive and
  negative support together.
\<close>

definition asti_some :: "('r \<Rightarrow> tv5) \<Rightarrow> bool" where
  "asti_some V \<longleftrightarrow> (\<exists>r. fde5.koti_of (V r) = K1)"

definition nasti_some :: "('r \<Rightarrow> tv5) \<Rightarrow> bool" where
  "nasti_some V \<longleftrightarrow> (\<exists>r. fde5.koti_of (V r) = K2)"

definition avak_some :: "('r \<Rightarrow> tv5) \<Rightarrow> bool" where
  "avak_some V \<longleftrightarrow> (\<exists>r. V r = E)"

fun naya_holds :: "('r \<Rightarrow> tv5) \<Rightarrow> bhanga \<Rightarrow> bool" where
  "naya_holds V B1 = asti_some V"
| "naya_holds V B2 = nasti_some V"
| "naya_holds V B3 = (asti_some V \<and> nasti_some V)"
| "naya_holds V B4 = avak_some V"
| "naya_holds V B5 = (asti_some V \<and> avak_some V)"
| "naya_holds V B6 = (nasti_some V \<and> avak_some V)"
| "naya_holds V B7 = (asti_some V \<and> nasti_some V \<and> avak_some V)"

text \<open>
  This reading is cumulative rather than an exclusive seven-way
  classification: support for the seventh mode supplies all three primitive
  supports and therefore every lower mode as well.
\<close>

theorem seventh_mode_supports_every_mode:
  assumes "naya_holds V B7"
  shows "naya_holds V b"
  using assms by (cases b) simp_all

text \<open>
  One respect is not enough: a constant family reproduces the classificatory
  reading, and the mixed modes are again empty.
\<close>

theorem single_naya_mixed_unsatisfiable:
  "\<not> naya_holds (\<lambda>_ :: nat. x) B5"
  "\<not> naya_holds (\<lambda>_ :: nat. x) B6"
  "\<not> naya_holds (\<lambda>_ :: nat. x) B7"
  by (auto simp: asti_some_def nasti_some_def avak_some_def fde5_koti_of_E)

subsubsection \<open>Three independent primitives\<close>

fun prims :: "bhanga \<Rightarrow> bool \<times> bool \<times> bool" where
  "prims B1 = (True, False, False)"
| "prims B2 = (False, True, False)"
| "prims B3 = (True, True, False)"
| "prims B4 = (False, False, True)"
| "prims B5 = (True, False, True)"
| "prims B6 = (False, True, True)"
| "prims B7 = (True, True, True)"

lemma range_prims:
  "range prims = {(True, False, False), (False, True, False), (True, True, False),
                  (False, False, True), (True, False, True), (False, True, True),
                  (True, True, True)}"
  by (simp add: UNIV_bhanga)

theorem three_primitives_generate:
  "inj prims"
  "range prims = {t. t \<noteq> (False, False, False)}"
proof -
  show "inj prims"
  proof (rule injI)
    fix b b' :: bhanga
    assume "prims b = prims b'"
    then show "b = b'" by (cases b; cases b') simp_all
  qed
next
  show "range prims = {t. t \<noteq> (False, False, False)}"
  proof (intro equalityI subsetI)
    fix t :: "bool \<times> bool \<times> bool"
    assume "t \<in> range prims"
    then show "t \<in> {t. t \<noteq> (False, False, False)}" by (auto simp: range_prims)
  next
    fix t :: "bool \<times> bool \<times> bool"
    assume "t \<in> {t. t \<noteq> (False, False, False)}"
    then obtain a n e where t: "t = (a, n, e)" and "a \<or> n \<or> e" by (cases t) auto
    then show "t \<in> range prims"
      by (cases a; cases n; cases e) (auto simp: range_prims t)
  qed
qed

lemma naya_holds_prims:
  "naya_holds V b \<longleftrightarrow>
     (fst (prims b) \<longrightarrow> asti_some V) \<and>
     (fst (snd (prims b)) \<longrightarrow> nasti_some V) \<and>
     (snd (snd (prims b)) \<longrightarrow> avak_some V)"
  by (cases b) auto

text \<open>
  The three primitives are independent: three respects suffice to switch
  each on or off without touching the others.
\<close>

definition naya3 :: "bool \<Rightarrow> bool \<Rightarrow> bool \<Rightarrow> nat \<Rightarrow> tv5" where
  "naya3 a n e i =
     (if i = 0 then (if a then Fin T else Fin B)
      else if i = 1 then (if n then Fin F else Fin B)
      else (if e then E else Fin B))"

theorem naya_primitives_independent:
  "asti_some (naya3 a n e) = a"
  "nasti_some (naya3 a n e) = n"
  "avak_some (naya3 a n e) = e"
proof -
  show "asti_some (naya3 a n e) = a"
    by (auto simp: asti_some_def naya3_def fde5_koti_values fde5_koti_of_E
             split: if_splits intro!: exI[of _ 0])
next
  show "nasti_some (naya3 a n e) = n"
    by (auto simp: nasti_some_def naya3_def fde5_koti_values fde5_koti_of_E
             split: if_splits intro!: exI[of _ "Suc 0"])
next
  show "avak_some (naya3 a n e) = e"
    by (auto simp: avak_some_def naya3_def split: if_splits intro!: exI[of _ 2])
qed

lemma naya_holds_naya3:
  "naya_holds (naya3 a n e) b \<longleftrightarrow>
     (fst (prims b) \<longrightarrow> a) \<and> (fst (snd (prims b)) \<longrightarrow> n) \<and> (snd (snd (prims b)) \<longrightarrow> e)"
  by (simp add: naya_holds_prims naya_primitives_independent)

definition wit :: "bhanga \<Rightarrow> nat \<Rightarrow> tv5" where
  "wit b = naya3 (fst (prims b)) (fst (snd (prims b))) (snd (snd (prims b)))"

theorem saptabhangi_separated_by_naya:
  assumes "b \<noteq> b'"
  shows "naya_holds (wit b) b \<noteq> naya_holds (wit b) b' \<or>
         naya_holds (wit b') b \<noteq> naya_holds (wit b') b'"
  using assms unfolding wit_def
  by (cases b; cases b') (simp_all add: naya_primitives_independent)

text \<open>
  All seven modes are satisfiable under the indexical reading, including
  the three that were empty on a single valuation.
\<close>

theorem all_seven_satisfiable: "naya_holds (wit b) b"
  by (cases b) (simp_all add: wit_def naya_primitives_independent)


subsubsection \<open>How many respects the mixed modes cost\<close>

text \<open>
  In the present model, the mixed modes need two distinct respects and the
  seventh needs three because their primitive supports are disjoint at an
  individual respect. The theorem is relative to these definitions.
\<close>

lemma koti_of_E_not_K1: "fde5.koti_of E \<noteq> K1" and koti_of_E_not_K2: "fde5.koti_of E \<noteq> K2"
  by (simp_all add: fde5_koti_of_E)

theorem mixed_modes_need_two_nayas:
  assumes "naya_holds V B5"
  shows "\<exists>r r'. V r \<noteq> V r'"
proof -
  from assms obtain r where r: "fde5.koti_of (V r) = K1" by (auto simp: asti_some_def)
  from assms obtain r' where r': "V r' = E" by (auto simp: avak_some_def)
  from r r' have "V r \<noteq> V r'" using koti_of_E_not_K1 by auto
  then show ?thesis by blast
qed

theorem seventh_mode_needs_three_nayas:
  assumes "naya_holds V B7"
  shows "\<exists>r1 r2 r3. V r1 \<noteq> V r2 \<and> V r1 \<noteq> V r3 \<and> V r2 \<noteq> V r3"
proof -
  from assms obtain r1 where r1: "fde5.koti_of (V r1) = K1" by (auto simp: asti_some_def)
  from assms obtain r2 where r2: "fde5.koti_of (V r2) = K2" by (auto simp: nasti_some_def)
  from assms obtain r3 where r3: "V r3 = E" by (auto simp: avak_some_def)
  have "V r1 \<noteq> V r2" using r1 r2 by auto
  moreover have "V r1 \<noteq> V r3" using r1 r3 koti_of_E_not_K1 by auto
  moreover have "V r2 \<noteq> V r3" using r2 r3 koti_of_E_not_K2 by auto
  ultimately show ?thesis by blast
qed

text \<open>
  Putting the readings side by side: mode 5 is impossible on one valuation
  and holds on three respects. The difference is not in the logic but in
  what \<open>syat\<close> ranges over.
\<close>

theorem syat_is_indexical:
  "\<not> fde5.bh_holds x B5"
  "naya_holds (wit B5) B5"
  using fde5.mixed_modes_unsatisfiable all_seven_satisfiable by blast+


subsection \<open>Representative subfamilies for all seven predicates\<close>

text \<open>
  This small-model result preserves only the three existential supports of
  the current model. It preserves neither order, multiplicity, nor relations
  between respects. In particular it does not recover successive versus
  simultaneous predication: the \<open>E\<close> support is independent of the positive
  and negative supports. Witness selection uses Hilbert choice and is not
  an executable search over an arbitrary, possibly infinite, domain.

  An explicit domain set allows empty families in HOL, whose types are
  nonempty. Taking the domain to be \<open>UNIV\<close> recovers \<open>naya_holds\<close> exactly.
\<close>

definition naya_holds_on :: "('r \<Rightarrow> tv5) \<Rightarrow> 'r set \<Rightarrow> bhanga \<Rightarrow> bool" where
  "naya_holds_on V R b \<longleftrightarrow>
    (fst (prims b) \<longrightarrow> (\<exists>r\<in>R. fde5.koti_of (V r) = K1)) \<and>
    (fst (snd (prims b)) \<longrightarrow> (\<exists>r\<in>R. fde5.koti_of (V r) = K2)) \<and>
    (snd (snd (prims b)) \<longrightarrow> (\<exists>r\<in>R. V r = E))"

lemma naya_holds_on_UNIV: "naya_holds_on V UNIV b \<longleftrightarrow> naya_holds V b"
  by (simp add: naya_holds_on_def naya_holds_prims asti_some_def nasti_some_def avak_some_def)

definition support_representative :: "'r set \<Rightarrow> ('r \<Rightarrow> bool) \<Rightarrow> 'r set" where
  "support_representative R P =
    (if \<exists>r\<in>R. P r then {SOME r. r \<in> R \<and> P r} else {})"

lemma support_representative_subset: "support_representative R P \<subseteq> R"
proof (cases "\<exists>r\<in>R. P r")
  case True
  have "(SOME r. r \<in> R \<and> P r) \<in> R \<and> P (SOME r. r \<in> R \<and> P r)"
    by (rule someI_ex[where P="\<lambda>r. r \<in> R \<and> P r"]) (use True in blast)
  then show ?thesis by (simp add: support_representative_def True)
next
  case False
  then show ?thesis by (simp add: support_representative_def)
qed

lemma support_representative_finite: "finite (support_representative R P)"
  by (simp add: support_representative_def)

lemma support_representative_card: "card (support_representative R P) \<le> 1"
  by (simp add: support_representative_def)

lemma support_representative_exists:
  "(\<exists>r\<in>support_representative R P. P r) \<longleftrightarrow> (\<exists>r\<in>R. P r)"
proof (cases "\<exists>r\<in>R. P r")
  case True
  have "(SOME r. r \<in> R \<and> P r) \<in> R \<and> P (SOME r. r \<in> R \<and> P r)"
    by (rule someI_ex[where P="\<lambda>r. r \<in> R \<and> P r"]) (use True in blast)
  then show ?thesis by (simp add: support_representative_def True)
next
  case False
  then show ?thesis by (simp add: support_representative_def)
qed

definition representative_nayas :: "('r \<Rightarrow> tv5) \<Rightarrow> 'r set \<Rightarrow> 'r set" where
  "representative_nayas V R =
    support_representative R (\<lambda>r. fde5.koti_of (V r) = K1) \<union>
    support_representative R (\<lambda>r. fde5.koti_of (V r) = K2) \<union>
    support_representative R (\<lambda>r. V r = E)"

lemma representative_nayas_subset: "representative_nayas V R \<subseteq> R"
  by (simp add: representative_nayas_def support_representative_subset)

lemma representative_nayas_finite: "finite (representative_nayas V R)"
  by (simp add: representative_nayas_def support_representative_finite)

lemma representative_nayas_card: "card (representative_nayas V R) \<le> 3"
proof -
  let ?A = "support_representative R (\<lambda>r. fde5.koti_of (V r) = K1)"
  let ?N = "support_representative R (\<lambda>r. fde5.koti_of (V r) = K2)"
  let ?E = "support_representative R (\<lambda>r. V r = E)"
  have "card (?A \<union> ?N \<union> ?E) \<le> card ?A + card ?N + card ?E"
    using card_Un_le[of "?A \<union> ?N" ?E] card_Un_le[of ?A ?N] by arith
  also have "\<dots> \<le> 3"
    using support_representative_card[of R "\<lambda>r. fde5.koti_of (V r) = K1"]
      support_representative_card[of R "\<lambda>r. fde5.koti_of (V r) = K2"]
      support_representative_card[of R "\<lambda>r. V r = E"] by arith
  finally show ?thesis by (simp add: representative_nayas_def)
qed

lemma representative_nayas_preserve_primitives:
  "(\<exists>r\<in>representative_nayas V R. fde5.koti_of (V r) = K1) \<longleftrightarrow>
    (\<exists>r\<in>R. fde5.koti_of (V r) = K1)"
  "(\<exists>r\<in>representative_nayas V R. fde5.koti_of (V r) = K2) \<longleftrightarrow>
    (\<exists>r\<in>R. fde5.koti_of (V r) = K2)"
  "(\<exists>r\<in>representative_nayas V R. V r = E) \<longleftrightarrow> (\<exists>r\<in>R. V r = E)"
proof -
  have sub: "representative_nayas V R \<subseteq> R" by (rule representative_nayas_subset)
  show "(\<exists>r\<in>representative_nayas V R. fde5.koti_of (V r) = K1) \<longleftrightarrow>
    (\<exists>r\<in>R. fde5.koti_of (V r) = K1)"
    using sub support_representative_exists[of R "\<lambda>r. fde5.koti_of (V r) = K1"]
    unfolding representative_nayas_def by blast
  show "(\<exists>r\<in>representative_nayas V R. fde5.koti_of (V r) = K2) \<longleftrightarrow>
    (\<exists>r\<in>R. fde5.koti_of (V r) = K2)"
    using sub support_representative_exists[of R "\<lambda>r. fde5.koti_of (V r) = K2"]
    unfolding representative_nayas_def by blast
  show "(\<exists>r\<in>representative_nayas V R. V r = E) \<longleftrightarrow> (\<exists>r\<in>R. V r = E)"
    using sub support_representative_exists[of R "\<lambda>r. V r = E"]
    unfolding representative_nayas_def by blast
qed

theorem representative_nayas_preserve_all:
  "naya_holds_on V (representative_nayas V R) b \<longleftrightarrow> naya_holds_on V R b"
  by (simp add: naya_holds_on_def representative_nayas_preserve_primitives)

theorem naya_small_model:
  "\<exists>S\<subseteq>R. finite S \<and> card S \<le> 3 \<and>
    (\<forall>b. naya_holds_on V S b \<longleftrightarrow> naya_holds_on V R b)"
  by (rule exI[of _ "representative_nayas V R"])
    (simp add: representative_nayas_subset representative_nayas_finite
      representative_nayas_card representative_nayas_preserve_all)

theorem naya_small_model_UNIV:
  "\<exists>S. finite S \<and> card S \<le> 3 \<and>
    (\<forall>b. naya_holds_on V S b \<longleftrightarrow> naya_holds V b)"
  using naya_small_model[of UNIV V] by (simp add: naya_holds_on_UNIV)

theorem representative_nayas_empty: "representative_nayas V {} = {}"
  by (simp add: representative_nayas_def support_representative_def)

theorem representative_nayas_empty_of_no_support:
  assumes "\<not> (\<exists>r\<in>R. fde5.koti_of (V r) = K1)"
    "\<not> (\<exists>r\<in>R. fde5.koti_of (V r) = K2)" "\<not> (\<exists>r\<in>R. V r = E)"
  shows "representative_nayas V R = {}"
  using assms by (simp add: representative_nayas_def support_representative_def)

text \<open>
  The existing seventh-mode separation argument also supplies the lower
  bound for a finite restricted domain. Together with the upper bound,
  this makes three necessary and sufficient in the worst case.
\<close>

theorem seventh_mode_subfamily_lower_bound:
  assumes "finite S" "naya_holds_on V S B7"
  shows "3 \<le> card S"
proof -
  from assms obtain a b c where mem: "a \<in> S" "b \<in> S" "c \<in> S"
    and pos: "fde5.koti_of (V a) = K1" and neg: "fde5.koti_of (V b) = K2"
    and ineff: "V c = E" by (auto simp: naya_holds_on_def)
  have distinct: "a \<noteq> b" "a \<noteq> c" "b \<noteq> c"
    using pos neg ineff koti_of_E_not_K1 koti_of_E_not_K2 by auto
  have "card {a, b, c} \<le> card S" using assms mem by (intro card_mono) auto
  then show ?thesis using distinct by simp
qed

theorem naya_small_model_bound_sharp:
  "card (representative_nayas (wit B7) UNIV) = 3"
  "\<And>S. finite S \<Longrightarrow>
    (\<forall>b. naya_holds_on (wit B7) S b \<longleftrightarrow> naya_holds (wit B7) b) \<Longrightarrow>
    3 \<le> card S"
proof -
  have h7: "naya_holds (wit B7) B7" by (rule all_seven_satisfiable)
  have "naya_holds_on (wit B7) (representative_nayas (wit B7) UNIV) B7"
    using h7 by (simp add: representative_nayas_preserve_all naya_holds_on_UNIV)
  then have "3 \<le> card (representative_nayas (wit B7) UNIV)"
    by (rule seventh_mode_subfamily_lower_bound[OF representative_nayas_finite])
  then show "card (representative_nayas (wit B7) UNIV) = 3"
    using representative_nayas_card[of "wit B7" UNIV] by arith
  fix S
  assume "finite S" and "\<forall>b. naya_holds_on (wit B7) S b \<longleftrightarrow> naya_holds (wit B7) b"
  then show "3 \<le> card S"
    using h7 seventh_mode_subfamily_lower_bound[of S "wit B7"] by blast
qed


subsection \<open>A witnessed loss of observation-relation information\<close>

text \<open>
  This is a minimal modern enrichment by an observation relation, not a
  formalization of historical succession or simultaneity. The two witnesses
  have the very same valuation family, but one relation is empty and the
  other contains the single directed pair \<open>(0, 1)\<close>. Thus not even this
  relational bit can be recovered uniformly from the seven-predicate profile.
\<close>

record 'r naya_observation =
  naya_valuation :: "'r \<Rightarrow> tv5"
  naya_relation :: "'r \<Rightarrow> 'r \<Rightarrow> bool"

definition observation_variant :: "bool \<Rightarrow> nat naya_observation" where
  "observation_variant marked =
    \<lparr> naya_valuation = wit B7, naya_relation = \<lambda>r s. marked \<and> r = 0 \<and> s = 1 \<rparr>"

theorem observation_variants_same_profile:
  "naya_holds (naya_valuation (observation_variant False)) b \<longleftrightarrow>
    naya_holds (naya_valuation (observation_variant True)) b"
  by (simp add: observation_variant_def)

theorem observation_variants_different_relation:
  "\<not> naya_relation (observation_variant False) 0 1"
  "naya_relation (observation_variant True) 0 1"
  by (simp_all add: observation_variant_def)

theorem naya_profile_cannot_recover_relation:
  "\<not> (\<exists>recover :: (bhanga \<Rightarrow> bool) \<Rightarrow> bool.
    \<forall>obs :: nat naya_observation.
      recover (naya_holds (naya_valuation obs)) \<longleftrightarrow> naya_relation obs 0 1)"
proof
  assume "\<exists>recover :: (bhanga \<Rightarrow> bool) \<Rightarrow> bool.
    \<forall>obs :: nat naya_observation.
      recover (naya_holds (naya_valuation obs)) \<longleftrightarrow> naya_relation obs 0 1"
  then obtain recover where h: "\<And>obs :: nat naya_observation.
    recover (naya_holds (naya_valuation obs)) \<longleftrightarrow> naya_relation obs 0 1" by blast
  from h[of "observation_variant False"] h[of "observation_variant True"]
  show False by (simp add: observation_variant_def)
qed

end
