/- SPDX-License-Identifier: Apache-2.0 -/

import BuddhistComparativeLogic.Comparative.ChineseThought.MohistCanons
import BuddhistComparativeLogic.Buddhist.Pramana.Tibetan.Definitions

/-!
# Extension, name, and selection in a White Horse audit

This module gives a bounded semantic audit motivated by Gongsun Long's
*White Horse Discourse*.  It does not select one historical interpretation of
that text.  Instead it separates four claims that are easy to conflate:
extension inclusion, identity of public names, identity of meanings, and
identity of the feature requirements used to select an object.

The positive finite model makes every white horse a horse while retaining a
black horse as a witness that the extensions differ.  In that same model the
two names, meanings, and requests are distinct.  A second model reuses the
coextensive-feature example from `TibetanDefinitions` to show the converse
boundary: even equality of extensions need not identify the requirements
that generated them.  These results are semantic countermodels to particular
entailments; they are not a verdict about the intended conclusion of the
received dialogue.
-/

namespace BuddhistComparativeLogic.WhiteHorse

open BuddhistComparativeLogic.Apoha
open BuddhistComparativeLogic.ApohaFeatures

universe u v w

/-! ## Separate interfaces for denotation and selection -/

/-- A feature request records the conditions under which an object may be
selected.  It is deliberately a separate type from both a public name and an
extensional object predicate. -/
structure SearchRequest (Feature : Type v) where
  requires : Requirements Feature

/-- A small lexicon gives each public name an intensional gloss and a search
request.  Its denotation is generated through the existing component
semantics rather than stored as another unconstrained field. -/
structure Lexicon (Object : Type u) (Name : Type v) (Meaning : Type w)
    (Feature : Type) where
  profile : FeatureProfile Object Feature
  meaning : Name -> Meaning
  request : Name -> SearchRequest Feature

namespace Lexicon

variable {Object : Type u} {Name : Type v} {Meaning : Type w}
    {Feature : Type} (lexicon : Lexicon Object Name Meaning Feature)

/-- The extension generated by the feature requirement associated with a
name. -/
def extension (name : Name) : PredSet Object :=
  componentClass lexicon.profile (lexicon.request name).requires

/-- Extensional inclusion, kept weaker than equality of names or requests. -/
def Included (narrow broad : Name) : Prop :=
  forall object, lexicon.extension narrow object ->
    lexicon.extension broad object

/-- Two names happen to apply to exactly the same objects. -/
def Coextensive (left right : Name) : Prop :=
  lexicon.extension left = lexicon.extension right

end Lexicon

/-! ## A finite stable model -/

inductive StableAnimal where
  | whiteMare
  | blackStallion
  | whiteOx
  deriving DecidableEq, Repr

inductive StableFeature where
  | equine
  | white
  deriving DecidableEq, Repr

inductive StableName where
  | horse
  | whiteHorse
  deriving DecidableEq, Repr

inductive StableMeaning where
  | equineKind
  | whiteQualifiedEquine
  deriving DecidableEq, Repr

open StableAnimal StableFeature StableName StableMeaning

/-- The mare has both selected features, the stallion only equinity, and the
ox only whiteness. -/
def stableProfile : FeatureProfile StableAnimal StableFeature
  | .whiteMare, _ => True
  | .blackStallion, .equine => True
  | .blackStallion, .white => False
  | .whiteOx, .equine => False
  | .whiteOx, .white => True

def horseRequirement : Requirements StableFeature :=
  fun feature => feature = .equine

def whiteHorseRequirement : Requirements StableFeature :=
  fun feature => feature = .equine ∨ feature = .white

def stableLexicon :
    Lexicon StableAnimal StableName StableMeaning StableFeature where
  profile := stableProfile
  meaning
    | .horse => .equineKind
    | .whiteHorse => .whiteQualifiedEquine
  request
    | .horse => ⟨horseRequirement⟩
    | .whiteHorse => ⟨whiteHorseRequirement⟩

abbrev horseExtension : PredSet StableAnimal :=
  stableLexicon.extension .horse

abbrev whiteHorseExtension : PredSet StableAnimal :=
  stableLexicon.extension .whiteHorse

/-- In the feature-grounded model, every object satisfying the qualified
request also satisfies the unqualified equine request. -/
theorem white_horse_included_in_horse :
    stableLexicon.Included .whiteHorse .horse := by
  intro animal qualified feature required
  exact qualified feature (Or.inl required)

theorem white_mare_is_both :
    whiteHorseExtension .whiteMare /\ horseExtension .whiteMare := by
  constructor
  · intro feature _required
    cases feature <;> trivial
  · intro feature required
    subst feature
    trivial

theorem black_stallion_is_horse_not_white_horse :
    horseExtension .blackStallion /\
      ¬ whiteHorseExtension .blackStallion := by
  constructor
  · intro feature required
    subst feature
    trivial
  · intro qualified
    exact qualified .white (Or.inr rfl)

theorem white_ox_is_not_a_horse : ¬ horseExtension .whiteOx := by
  intro equine
  exact equine .equine rfl

/-- The strict inclusion provides a direct finite counterexample to replacing
the qualified extension by the unqualified one. -/
theorem white_horse_extension_strictly_included :
    stableLexicon.Included .whiteHorse .horse /\
      ¬ stableLexicon.Coextensive .whiteHorse .horse := by
  refine ⟨white_horse_included_in_horse, ?_⟩
  intro equalExtensions
  have atStallion := congrFun equalExtensions .blackStallion
  exact black_stallion_is_horse_not_white_horse.2
    (atStallion.mpr black_stallion_is_horse_not_white_horse.1)

theorem stable_names_distinct :
    (StableName.whiteHorse : StableName) ≠ .horse := by
  decide

theorem stable_meanings_distinct :
    stableLexicon.meaning .whiteHorse ≠ stableLexicon.meaning .horse := by
  decide

theorem stable_requirements_distinct :
    (stableLexicon.request .whiteHorse).requires ≠
      (stableLexicon.request .horse).requires := by
  intro equality
  have atWhite := congrFun equality StableFeature.white
  simp [stableLexicon, whiteHorseRequirement, horseRequirement] at atWhite

theorem stable_requests_distinct :
    stableLexicon.request .whiteHorse ≠ stableLexicon.request .horse := by
  intro equality
  exact stable_requirements_distinct
    (congrArg SearchRequest.requires equality)

/-- One inhabited finite model simultaneously validates extension inclusion
and refutes identity of name, meaning, and selection request.  Thus none of
those identities follows merely from the inclusion premise. -/
theorem inclusion_does_not_identify_name_meaning_or_request :
    stableLexicon.Included .whiteHorse .horse /\
      (StableName.whiteHorse : StableName) ≠ .horse /\
      stableLexicon.meaning .whiteHorse ≠ stableLexicon.meaning .horse /\
      stableLexicon.request .whiteHorse ≠ stableLexicon.request .horse /\
      whiteHorseExtension .whiteMare /\
      horseExtension .blackStallion := by
  exact ⟨white_horse_included_in_horse, stable_names_distinct,
    stable_meanings_distinct, stable_requests_distinct,
    white_mare_is_both.1, black_stallion_is_horse_not_white_horse.1⟩

/-! ## Reuse of the Mohist naming audit -/

inductive StableKind where
  | whiteEquine
  | otherEquine
  | whiteBovine
  deriving DecidableEq, Repr

/-- The finer kind index lets the existing Mohist `Naming` interface audit
actual designation and admitted kinds without collapsing the two names. -/
def stableNaming :
    BuddhistComparativeLogic.MohistCanons.Naming StableAnimal StableName StableKind where
  kindOf
    | .whiteMare => .whiteEquine
    | .blackStallion => .otherEquine
    | .whiteOx => .whiteBovine
  designates name animal := stableLexicon.extension name animal
  admits
    | .horse, kind => kind = .whiteEquine ∨ kind = .otherEquine
    | .whiteHorse, kind => kind = .whiteEquine

/-- The finite lexicon satisfies the pre-existing name/object regularity
check.  This compatibility does not add an equality between the names. -/
theorem stable_naming_regular : stableNaming.Regular := by
  intro name animal
  cases name <;> cases animal <;>
    simp [BuddhistComparativeLogic.MohistCanons.Naming.Fits, stableNaming,
      Lexicon.extension, stableLexicon, componentClass, stableProfile,
      horseRequirement, whiteHorseRequirement]

/-! ## Reuse of the Tibetan definition triad -/

def whiteHorseTriad :
    BuddhistComparativeLogic.TibetanDefinitions.DefinitionTriad
      StableAnimal StableFeature where
  hasFeatures := stableProfile
  requires := whiteHorseRequirement
  definiendum := whiteHorseExtension
  basis := .whiteMare

theorem white_horse_triad_coextensive_and_instantiated :
    whiteHorseTriad.Coextensive /\ whiteHorseTriad.BasisFits := by
  exact ⟨fun _ => Iff.rfl, white_mare_is_both.1⟩

/-! ## Coextension does not recover the request -/

open BuddhistComparativeLogic.TibetanDefinitions

def twinLeftRequest : SearchRequest TwinFeature := ⟨requiresLeft⟩
def twinRightRequest : SearchRequest TwinFeature := ⟨requiresRight⟩

theorem twin_requests_distinct : twinLeftRequest ≠ twinRightRequest := by
  intro equality
  exact twin_requirements_distinct
    (congrArg SearchRequest.requires equality)

/-- The inherited two-object profile has two coextensive generated classes
but distinct feature requests.  Equality of actual extensions therefore does
not, without an additional intensional principle, recover request identity. -/
theorem same_extension_does_not_determine_search_request :
    componentClass twinProfile twinLeftRequest.requires =
        componentClass twinProfile twinRightRequest.requires /\
      twinLeftRequest ≠ twinRightRequest := by
  exact ⟨twin_conditions_coextensive, twin_requests_distinct⟩

end BuddhistComparativeLogic.WhiteHorse
